@startuml
title StockManagementクラス図(PUSH)
class StockManagement{
    StockManagement()
    getHandling() : ItemHandling
    getShipping() : Item
}
class Handling{
    value : ItemHandling
    Handling(stock : Stock, shipping : Shipping)
    updateAvailable(...)  : void
    updateRequest(...)  : void
    getValue() : ItemHandling
}
class Shipping{
    value : Item
    Shipping()
    updateHandling(itemHandling : ItemHandling) : void
    getValue() : Item
}
StockManagement -->"1" Handling :handling
StockManagement -->"1" Shipping  :shipping
Handling ->"1" Shipping : shipping

@enduml